// <auto-generated/>
// This file was automatically generated by generate-asset-paths.mjs.
// Strongly-typed static asset paths for the unified Assets package.
// Categories are first-class static classes directly in namespace Assets.Constants.
// Usage in Razor: @Images.LandingHeroMain, @Scripts.MaterialWebBundle.

#nullable enable
#pragma warning disable

namespace Assets.Constants
{
    public static class Images
    {
        public const string BackgroundArt = "_content/Assets/img/background-art.png";
        public const string Favicon = "_content/Assets/img/favicon.png";
        public const string Game = "_content/Assets/img/game.svg";
        public const string Heart = "_content/Assets/img/heart.png";
        public const string Hero = "_content/Assets/img/hero.svg";
        public const string Icon192 = "_content/Assets/img/icon-192.png";
        public const string Icon512 = "_content/Assets/img/icon-512.png";
        public const string Landing3dWorkspace = "_content/Assets/img/landing_3d_workspace.png";
        public const string LandingAiDashboard = "_content/Assets/img/landing_ai_dashboard.png";
        public const string LandingHeroMain = "_content/Assets/img/landing_hero_main.png";
        public const string LandingQrStudio = "_content/Assets/img/landing_qr_studio.png";
        public const string LandingSmartKiosk = "_content/Assets/img/landing_smart_kiosk.png";
        public const string Loading = "_content/Assets/img/loading.webp";
        public const string PartyWumpus = "_content/Assets/img/party_wumpus.gif";
        public const string Smoke = "_content/Assets/img/Smoke.gif";
        public const string Socratic = "_content/Assets/img/Socratic.svg";
        public const string SvgviewerOutput = "_content/Assets/img/svgviewer-output.svg";
        public const string Tv = "_content/Assets/img/tv.svg";
    }

    public static class Scripts
    {
        public const string App = "_content/Assets/lib/app.js";
        public const string LoadingIcon = "_content/Assets/lib/pdfjs-dist/dist/web/images/loading-icon.gif";
        public const string MarkedEsm = "_content/Assets/lib/marked/dist/marked.esm.js";
        public const string MaterialColorUtilitiesBundle = "_content/Assets/js/material-color-utilities.bundle.js";
        public const string MaterialWebBundle = "_content/Assets/js/material-web.bundle.js";
        public const string OauthPopupHelper = "_content/Assets/js/oauthPopupHelper.js";
        public const string PasskeyHelper = "_content/Assets/js/passkeyHelper.js";
        public const string PdfMin = "_content/Assets/lib/pdfjs-dist/dist/build/pdf.min.mjs";
        public const string PdfViewer = "_content/Assets/lib/pdfjs-dist/dist/web/pdf_viewer.mjs";
        public const string PdfWorkerMin = "_content/Assets/lib/pdfjs-dist/dist/build/pdf.worker.min.mjs";
        public const string PurifyEs = "_content/Assets/lib/dompurify/dist/purify.es.mjs";
        public const string RemoteSupportWebRtc = "_content/Assets/js/remoteSupportWebRtc.js";
        public const string SrcDefender = "_content/Assets/lib/src-defender.js";
        public const string TelegramHelper = "_content/Assets/js/telegramHelper.js";
        public const string Viewer = "_content/Assets/lib/pdf_viewer/viewer.mjs";
    }

    public static class Styles
    {
        public const string StylesFile = "_content/Assets/css/styles.css";
        public const string StylesBundleMin = "_content/Assets/css/styles.bundle.min.css";
    }

    public static class Fonts
    {
        public const string MaterialSymbolsOutlined = "_content/Assets/fonts/MaterialSymbolsOutlined/Material-Symbols-Outlined.woff2";
        public const string Montserrat = "_content/Assets/fonts/montserrat.css";
        public const string MontserratBlack = "_content/Assets/fonts/Montserrat/static/Montserrat-Black.ttf";
        public const string MontserratBlackItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf";
        public const string MontserratBold = "_content/Assets/fonts/Montserrat/static/Montserrat-Bold.ttf";
        public const string MontserratBoldItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf";
        public const string MontserratExtraBold = "_content/Assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf";
        public const string MontserratExtraBoldItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf";
        public const string MontserratExtraLight = "_content/Assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf";
        public const string MontserratExtraLightItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf";
        public const string MontserratItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-Italic.ttf";
        public const string MontserratItalicVariableFontWght = "_content/Assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf";
        public const string MontserratLight = "_content/Assets/fonts/Montserrat/static/Montserrat-Light.ttf";
        public const string MontserratLightItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf";
        public const string MontserratMedium = "_content/Assets/fonts/Montserrat/static/Montserrat-Medium.ttf";
        public const string MontserratMediumItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf";
        public const string MontserratRegular = "_content/Assets/fonts/Montserrat/static/Montserrat-Regular.ttf";
        public const string MontserratSemiBold = "_content/Assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf";
        public const string MontserratSemiBoldItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf";
        public const string MontserratThin = "_content/Assets/fonts/Montserrat/static/Montserrat-Thin.ttf";
        public const string MontserratThinItalic = "_content/Assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf";
        public const string MontserratVariableFontWght = "_content/Assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf";
        public const string OFL = "_content/Assets/fonts/Roboto/OFL.txt";
        public const string README = "_content/Assets/fonts/Roboto/README.txt";
        public const string Roboto = "_content/Assets/fonts/roboto.css";
        public const string RobotoBlack = "_content/Assets/fonts/Roboto/static/Roboto-Black.ttf";
        public const string RobotoBlackItalic = "_content/Assets/fonts/Roboto/static/Roboto-BlackItalic.ttf";
        public const string RobotoBold = "_content/Assets/fonts/Roboto/static/Roboto-Bold.ttf";
        public const string RobotoBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto-BoldItalic.ttf";
        public const string RobotoCondensedBlack = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Black.ttf";
        public const string RobotoCondensedBlackItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-BlackItalic.ttf";
        public const string RobotoCondensedBold = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Bold.ttf";
        public const string RobotoCondensedBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-BoldItalic.ttf";
        public const string RobotoCondensedExtraBold = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-ExtraBold.ttf";
        public const string RobotoCondensedExtraBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-ExtraBoldItalic.ttf";
        public const string RobotoCondensedExtraLight = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-ExtraLight.ttf";
        public const string RobotoCondensedExtraLightItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-ExtraLightItalic.ttf";
        public const string RobotoCondensedItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Italic.ttf";
        public const string RobotoCondensedLight = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Light.ttf";
        public const string RobotoCondensedLightItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-LightItalic.ttf";
        public const string RobotoCondensedMedium = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Medium.ttf";
        public const string RobotoCondensedMediumItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-MediumItalic.ttf";
        public const string RobotoCondensedRegular = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Regular.ttf";
        public const string RobotoCondensedSemiBold = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-SemiBold.ttf";
        public const string RobotoCondensedSemiBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-SemiBoldItalic.ttf";
        public const string RobotoCondensedThin = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-Thin.ttf";
        public const string RobotoCondensedThinItalic = "_content/Assets/fonts/Roboto/static/Roboto_Condensed-ThinItalic.ttf";
        public const string RobotoExtraBold = "_content/Assets/fonts/Roboto/static/Roboto-ExtraBold.ttf";
        public const string RobotoExtraBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto-ExtraBoldItalic.ttf";
        public const string RobotoExtraLight = "_content/Assets/fonts/Roboto/static/Roboto-ExtraLight.ttf";
        public const string RobotoExtraLightItalic = "_content/Assets/fonts/Roboto/static/Roboto-ExtraLightItalic.ttf";
        public const string RobotoItalic = "_content/Assets/fonts/Roboto/static/Roboto-Italic.ttf";
        public const string RobotoItalicVariableFont = "_content/Assets/fonts/Roboto/Roboto-Italic-VariableFont.ttf";
        public const string RobotoLight = "_content/Assets/fonts/Roboto/static/Roboto-Light.ttf";
        public const string RobotoLightItalic = "_content/Assets/fonts/Roboto/static/Roboto-LightItalic.ttf";
        public const string RobotoMedium = "_content/Assets/fonts/Roboto/static/Roboto-Medium.ttf";
        public const string RobotoMediumItalic = "_content/Assets/fonts/Roboto/static/Roboto-MediumItalic.ttf";
        public const string RobotoRegular = "_content/Assets/fonts/Roboto/static/Roboto-Regular.ttf";
        public const string RobotoSemiBold = "_content/Assets/fonts/Roboto/static/Roboto-SemiBold.ttf";
        public const string RobotoSemiBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto-SemiBoldItalic.ttf";
        public const string RobotoSemiCondensedBlack = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Black.ttf";
        public const string RobotoSemiCondensedBlackItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-BlackItalic.ttf";
        public const string RobotoSemiCondensedBold = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Bold.ttf";
        public const string RobotoSemiCondensedBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-BoldItalic.ttf";
        public const string RobotoSemiCondensedExtraBold = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-ExtraBold.ttf";
        public const string RobotoSemiCondensedExtraBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-ExtraBoldItalic.ttf";
        public const string RobotoSemiCondensedExtraLight = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-ExtraLight.ttf";
        public const string RobotoSemiCondensedExtraLightItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-ExtraLightItalic.ttf";
        public const string RobotoSemiCondensedItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Italic.ttf";
        public const string RobotoSemiCondensedLight = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Light.ttf";
        public const string RobotoSemiCondensedLightItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-LightItalic.ttf";
        public const string RobotoSemiCondensedMedium = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Medium.ttf";
        public const string RobotoSemiCondensedMediumItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-MediumItalic.ttf";
        public const string RobotoSemiCondensedRegular = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Regular.ttf";
        public const string RobotoSemiCondensedSemiBold = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-SemiBold.ttf";
        public const string RobotoSemiCondensedSemiBoldItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-SemiBoldItalic.ttf";
        public const string RobotoSemiCondensedThin = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-Thin.ttf";
        public const string RobotoSemiCondensedThinItalic = "_content/Assets/fonts/Roboto/static/Roboto_SemiCondensed-ThinItalic.ttf";
        public const string RobotoThin = "_content/Assets/fonts/Roboto/static/Roboto-Thin.ttf";
        public const string RobotoThinItalic = "_content/Assets/fonts/Roboto/static/Roboto-ThinItalic.ttf";
        public const string RobotoVariableFont = "_content/Assets/fonts/Roboto/Roboto-VariableFont.ttf";
    }

    public static class Maps
    {
        public const string Dark = "_content/Assets/maps/dark.json";
        public const string Light = "_content/Assets/maps/light.json";
        public const string MapBootstrap = "_content/Assets/maps/map-bootstrap.js";
    }

    public static class AppManifest
    {
        public const string HealthNutritionGuide = "_content/Assets/data/health_nutrition_guide.pdf";
        public const string Manifest = "_content/Assets/manifest.webmanifest";
        public const string MaterialTheme = "_content/Assets/docs/material-theme.json";
    }

}
