<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Configurations>Debug;Release;LocalDebug;Runner;Cluster</Configurations>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DisableStaticWebAssetsCompression>true</DisableStaticWebAssetsCompression>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
