// <auto-generated/>
// This file was automatically generated by generate-css-classes.mjs.
// Strongly-typed CSS class constants for Socratic Blazor components.
// Design System CSS Dictionary (Public API).

#nullable enable
#pragma warning disable

namespace Material.Web;

/// <summary>
/// Strongly-typed CSS class selectors for Socratic Material Design 3 components.
/// Provides compile-time safety and IDE IntelliSense.
/// </summary>
public static class M3
{
    public static class Avatar
    {
        public const string Button = "avatar-button";
        public const string Contacts = "contacts";
        public const string Container = "avatar-container";
        public const string Content = "content";
        public const string FaceidProfileModal = "faceid-profile-modal";
        public const string Headline = "headline";
        public const string MaterialSymbolsOutlined = "material-symbols-outlined";
        public const string MaterialTextField = "material-text-field";
        public const string Row = "row";
    }

    public static class Badge
    {
        public const string Active = "badge-active";
        public const string BackButton = "m3-back-button";
        public const string BackIcon = "m3-back-icon";
        public const string Blocked = "badge-blocked";
        public const string Canceled = "canceled";
        public const string Cancelled = "badge-cancelled";
        public const string Collected = "collected";
        public const string Collecting = "collecting";
        public const string Completed = "badge-completed";
        public const string CountBadge = "m3-count-badge";
        public const string Counter = "badge-counter";
        public const string Created = "created";
        public const string Error = "error";
        public const string Expired = "badge-expired";
        public const string Icon = "badge-icon";
        public const string Info = "info";
        public const string ItemQtyBadge = "item-qty-badge";
        public const string ItemStatusPill = "item-status-pill";
        public const string ItemsCountBadge = "items-count-badge";
        public const string KdsQtyBadge = "kds-qty-badge";
        public const string KdsStatusTag = "kds-status-tag";
        public const string Made = "made";
        public const string Making = "badge-making";
        public const string MaterialCounter = "material-counter";
        public const string None = "badge-none";
        public const string OrderStatusBadge = "order-status-badge";
        public const string Paid = "paid";
        public const string Paused = "badge-paused";
        public const string PillBadge = "m3-pill-badge";
        public const string Pro = "badge-pro";
        public const string Pulse = "pulse";
        public const string Ready = "badge-ready";
        public const string ReadyBadge = "ready-badge";
        public const string Root = "m3-badge";
        public const string Secondary = "secondary";
        public const string Shipping = "shipping";
        public const string StatusBadge = "m3-status-badge";
        public const string StatusCanceled = "status-canceled";
        public const string StatusCollected = "status-collected";
        public const string StatusCollecting = "status-collecting";
        public const string StatusCompleted = "status-completed";
        public const string StatusCreated = "status-created";
        public const string StatusDot = "m3-status-dot";
        public const string StatusMade = "status-made";
        public const string StatusMaking = "status-making";
        public const string StatusPaid = "status-paid";
        public const string StatusShipping = "status-shipping";
        public const string Success = "success";
        public const string Tertiary = "tertiary";
        public const string Trial = "badge-trial";
        public const string Verified = "badge-verified";
        public const string Warning = "warning";
        public const string WithAds = "badge-with-ads";
    }

    public static class Cards
    {
        public const string Actions = "m3-card-actions";
        public const string Body = "m3-card-body";
        public const string Card = "m3-card";
        public const string Elevated = "m3-card-elevated";
        public const string Filled = "m3-card-filled";
        public const string Footer = "m3-card-footer";
        public const string Glass = "m3-card-glass";
        public const string GlassCard = "glass-card";
        public const string Grid = "card-grid";
        public const string Header = "m3-card-header";
        public const string Interactive = "m3-card-interactive";
        public const string MaterialSymbolsOutlined = "material-symbols-outlined";
        public const string Media = "m3-card-media";
        public const string MediaCard = "m3-media-card";
        public const string MediaPlaceholder = "m3-card-media-placeholder";
        public const string OrgCard = "org-card";
        public const string OrgCardContent = "org-card-content";
        public const string OrgCardDesc = "org-card-desc";
        public const string OrgCardName = "org-card-name";
        public const string OrgMedia = "org-media";
        public const string OrgMediaPlaceholder = "org-media-placeholder";
        public const string Outlined = "m3-card-outlined";
        public const string PaddingLg = "m3-card-padding-lg";
        public const string PaddingMd = "m3-card-padding-md";
        public const string PaddingSm = "m3-card-padding-sm";
        public const string PriceTag = "price-tag";
        public const string ProductCard = "product-card";
        public const string ProductTitle = "product-title";
        public const string RowLabel = "m3-row-label";
        public const string RowValue = "m3-row-value";
        public const string Subtitle = "m3-card-subtitle";
        public const string SummaryActions = "m3-summary-actions";
        public const string SummaryBackLink = "summary-back-link";
        public const string SummaryCard = "m3-summary-card";
        public const string SummaryDivider = "m3-summary-divider";
        public const string SummaryRow = "m3-summary-row";
        public const string SummaryRows = "m3-summary-rows";
        public const string SummaryTitle = "m3-summary-title";
        public const string Title = "m3-card-title";
        public const string TotalLabel = "m3-total-label";
        public const string TotalRow = "m3-total-row";
        public const string TotalValue = "m3-total-value";
        public const string WishlistCardFooter = "wishlist-card-footer";
        public const string WishlistContent = "wishlist-content";
        public const string WishlistDescText = "wishlist-desc-text";
        public const string WishlistDetailsDesc = "wishlist-details-desc";
        public const string WishlistDetailsDl = "wishlist-details-dl";
        public const string WishlistDetailsImages = "wishlist-details-images";
        public const string WishlistDetailsPrice = "wishlist-details-price";
        public const string WishlistDetailsPriceRow = "wishlist-details-price-row";
        public const string WishlistDetailsThumb = "wishlist-details-thumb";
        public const string WishlistMedia = "wishlist-media";
        public const string WishlistPlaceholder = "wishlist-placeholder";
        public const string WishlistPriceTag = "wishlist-price-tag";
        public const string WishlistTitleText = "wishlist-title-text";
        public const string WishlistWishBtn = "wishlist-wish-btn";
    }

    public static class Chip
    {
        public const string Active = "active";
        public const string FilterChip = "m3-filter-chip";
        public const string FilterChipCount = "m3-filter-chip-count";
        public const string FilterChipIcon = "m3-filter-chip-icon";
    }

    public static class Dialog
    {
        public const string Actions = "m3-dialog-actions";
        public const string Backdrop = "m3-dialog-backdrop";
        public const string BtnPrimary = "m3-dialog-btn-primary";
        public const string CloseBtn = "m3-dialog-close-btn";
        public const string ConfigDialog = "m3-config-dialog";
        public const string Description = "m3-dialog-description";
        public const string Header = "m3-dialog-header";
        public const string Icon = "m3-dialog-icon";
        public const string ModalBackdrop = "m3-modal-backdrop";
        public const string OptionsList = "m3-dialog-options-list";
        public const string Surface = "m3-dialog-surface";
        public const string TitleGroup = "m3-dialog-title-group";
        public const string ToggleDesc = "m3-dialog-toggle-desc";
        public const string ToggleIcon = "m3-dialog-toggle-icon";
        public const string ToggleItem = "m3-dialog-toggle-item";
        public const string ToggleText = "m3-dialog-toggle-text";
        public const string ToggleTitle = "m3-dialog-toggle-title";
    }

    public static class EmptyState
    {
        public const string Action = "m3-empty-state-action";
        public const string BtnPrimaryLink = "btn-primary-link";
        public const string ColumnEmpty = "column-empty";
        public const string Desc = "m3-empty-state-desc";
        public const string EmptyColumn = "m3-empty-column";
        public const string EmptyColumnIcon = "m3-empty-column-icon";
        public const string EmptyMiniIcon = "empty-mini-icon";
        public const string Icon = "m3-empty-state-icon";
        public const string KdsEmptyCol = "kds-empty-col";
        public const string KdsEmptyIcon = "kds-empty-icon";
        public const string KioskEmptyIcon = "kiosk-empty-icon";
        public const string KioskEmptyState = "kiosk-empty-state";
        public const string NotFoundIcon = "not-found-icon";
        public const string PosEmptyIcon = "pos-empty-icon";
        public const string PosEmptyState = "pos-empty-state";
        public const string Root = "m3-empty-state";
        public const string StoreNotFound = "store-not-found";
        public const string Title = "m3-empty-state-title";
    }

    public static class Form
    {
        public const string BannerError = "m3-banner-error";
        public const string Counter = "m3-counter";
        public const string ErrorBanner = "error-banner";
        public const string ErrorIcon = "error-icon";
        public const string Fieldset = "m3-fieldset";
        public const string Grid = "m3-form-grid";
        public const string Invalid = "invalid";
        public const string Legend = "m3-legend";
        public const string MaterialCounter = "material-counter";
        public const string Modified = "modified";
        public const string TwoCols = "two-cols";
        public const string Valid = "valid";
        public const string ValidationMessage = "validation-message";
    }

    public static class InfoGrid
    {
        public const string InfoItem = "m3-info-item";
        public const string InfoLabel = "m3-info-label";
        public const string InfoValue = "m3-info-value";
        public const string Root = "m3-info-grid";
    }

    public static class Picker
    {
        public const string Active = "active";
        public const string ArchiveType = "m3-archive-type";
        public const string AudioType = "m3-audio-type";
        public const string Badge = "picker-badge";
        public const string BodySubtext = "body-subtext";
        public const string BookingPickerCard = "booking-picker-card";
        public const string BookingSummaryBanner = "booking-summary-banner";
        public const string CanvasCard = "canvas-card";
        public const string CanvasHeader = "canvas-header";
        public const string CanvasWrapper = "canvas-wrapper";
        public const string ColorBadgeSwatch = "color-badge-swatch";
        public const string CompactBox = "picker-compact-box";
        public const string CustomPreview = "picker-custom-preview";
        public const string DatePresetsRow = "date-presets-row";
        public const string DayDot = "picker-day-dot";
        public const string Disabled = "disabled";
        public const string DocType = "m3-doc-type";
        public const string Dragging = "dragging";
        public const string FileAddBtnLabel = "file-add-btn-label";
        public const string FileCard = "file-card";
        public const string FileGrid = "file-grid";
        public const string FileInfo = "file-info";
        public const string FileInputHidden = "file-input-hidden";
        public const string FileName = "file-name";
        public const string FileOverlay = "file-overlay";
        public const string FilePickerContainer = "file-picker-container";
        public const string FilePreviewArea = "file-preview-area";
        public const string GenericType = "m3-generic-type";
        public const string HeaderRow = "picker-header-row";
        public const string Headline = "headline";
        public const string HexInput = "picker-hex-input";
        public const string HexPrefix = "picker-hex-prefix";
        public const string HexWrapper = "picker-hex-wrapper";
        public const string IconBadge = "picker-icon-badge";
        public const string IconPreview = "icon-preview";
        public const string ImagePreview = "image-preview";
        public const string IsOpen = "is-open";
        public const string IsSelected = "is-selected";
        public const string LabelTitle = "label-title";
        public const string LangChevron = "lang-chevron";
        public const string LangChipActive = "lang-chip--active";
        public const string LangChipBtn = "lang-chip-btn";
        public const string LangCurrentLabel = "lang-current-label";
        public const string LangDropdownMenu = "lang-dropdown-menu";
        public const string LangDropdownWrapper = "lang-dropdown-wrapper";
        public const string LangGlobeIcon = "lang-globe-icon";
        public const string LangInlineGrid = "lang-inline-grid";
        public const string LangMenuItem = "lang-menu-item";
        public const string LangPillBtn = "lang-pill-btn";
        public const string LangSelect = "lang-select";
        public const string Md3ClosedBadge = "md3-closed-badge";
        public const string Md3DialogActionsRow = "md3-dialog-actions-row";
        public const string Md3DialogHeadline = "md3-dialog-headline";
        public const string Md3HeadlineIcon = "md3-headline-icon";
        public const string Md3PresetsLabel = "md3-presets-label";
        public const string Md3PresetsRow = "md3-presets-row";
        public const string Md3PresetsSection = "md3-presets-section";
        public const string Md3ScheduleDayCard = "md3-schedule-day-card";
        public const string Md3ScheduleDayLeft = "md3-schedule-day-left";
        public const string Md3ScheduleDays = "md3-schedule-days";
        public const string Md3ScheduleHeader = "md3-schedule-header";
        public const string Md3SchedulePicker = "md3-schedule-picker";
        public const string Md3ScheduleSubtitle = "md3-schedule-subtitle";
        public const string Md3ScheduleTimeGroup = "md3-schedule-time-group";
        public const string Md3TimeInput = "md3-time-input";
        public const string Md3TimeLabel = "md3-time-label";
        public const string Md3TimePickerBox = "md3-time-picker-box";
        public const string Md3TimeSeparator = "md3-time-separator";
        public const string NativeInput = "picker-native-input";
        public const string NewBadge = "new-badge";
        public const string OptionAddPrice = "option-add-price";
        public const string OptionFieldset = "option-fieldset";
        public const string OptionItemRow = "option-item-row";
        public const string OptionsListContainer = "options-list-container";
        public const string PaletteGrid = "picker-palette-grid";
        public const string PaletteSwatch = "picker-palette-swatch";
        public const string PdfType = "m3-pdf-type";
        public const string PopoverFooter = "picker-popover-footer";
        public const string PopoverHeader = "picker-popover-header";
        public const string PopoverPanel = "picker-popover-panel";
        public const string PopoverTitle = "picker-popover-title";
        public const string PreviewText = "picker-preview-text";
        public const string PriceBox = "price-box";
        public const string PriceLabel = "price-label";
        public const string PriceValue = "price-value";
        public const string RequiredBadge = "required-badge";
        public const string ResourceTabs = "resource-tabs";
        public const string Selected = "selected";
        public const string SheetType = "m3-sheet-type";
        public const string SlotsChipSet = "slots-chip-set";
        public const string SummaryActions = "summary-actions";
        public const string SummaryCheckIcon = "summary-check-icon";
        public const string SummaryDate = "summary-date";
        public const string SummaryLeft = "summary-left";
        public const string SummaryTextBox = "summary-text-box";
        public const string SummaryTitle = "summary-title";
        public const string Swatch = "picker-swatch";
        public const string SwatchCheck = "picker-swatch-check";
        public const string SwatchWrapper = "picker-swatch-wrapper";
        public const string TimeFieldset = "time-fieldset";
        public const string TitleRow = "picker-title-row";
        public const string TriggerActions = "picker-trigger-actions";
        public const string TriggerCard = "picker-trigger-card";
        public const string TriggerLeft = "picker-trigger-left";
        public const string TriggerText = "picker-trigger-text";
        public const string TriggerTitle = "picker-trigger-title";
        public const string UploadCard = "upload-card";
        public const string UploadIcon = "upload-icon";
        public const string UploadSubtext = "upload-subtext";
        public const string UploadText = "upload-text";
        public const string UploadZoneLabel = "upload-zone-label";
        public const string VariantDialogActions = "variant-dialog-actions";
        public const string VariantDialogBody = "variant-dialog-body";
        public const string VariantDialogHeader = "variant-dialog-header";
        public const string VariantDialogSubtext = "variant-dialog-subtext";
        public const string VariantDialogTitle = "variant-dialog-title";
        public const string VariantsChipSet = "variants-chip-set";
        public const string VideoType = "m3-video-type";
        public const string Web = "Web";
        public const string WeekMiniDots = "picker-week-mini-dots";
    }

    public static class Progress
    {
        public const string Container = "m3-progress-container";
        public const string Fill = "m3-progress-fill";
        public const string Labels = "m3-progress-labels";
        public const string ProgressBarBg = "progress-bar-bg";
        public const string ProgressBarContainer = "progress-bar-container";
        public const string ProgressBarFill = "progress-bar-fill";
        public const string ProgressLabels = "progress-labels";
        public const string Track = "m3-progress-track";
    }

    public static class Search
    {
        public const string Container = "m3-search-container";
        public const string MaterialSearchContainer = "material-search-container";
        public const string MaterialTextField = "material-text-field";
    }

    public static class SegmentedButton
    {
        public const string Active = "active";
        public const string AnalyticsDatePickerTrigger = "analytics-date-picker-trigger";
        public const string AnalyticsHeaderControls = "analytics-header-controls";
        public const string AnalyticsModeBtn = "analytics-mode-btn";
        public const string AnalyticsModePillGroup = "analytics-mode-pill-group";
        public const string HeaderControls = "m3-header-controls";
        public const string PeriodPickerTrigger = "m3-period-picker-trigger";
        public const string SegmentedBtn = "m3-segmented-btn";
        public const string SegmentedPillGroup = "m3-segmented-pill-group";
    }

    public static class Skeleton
    {
        public const string Card = "m3-skeleton-card";
        public const string Circle = "m3-skeleton-circle";
        public const string Root = "m3-skeleton";
        public const string Short = "m3-short";
        public const string Text = "m3-skeleton-text";
    }

    public static class Table
    {
        public const string ActionsBar = "m3-table-actions-bar";
        public const string ActionsColumn = "actions-column";
        public const string AmountCell = "m3-amount-cell";
        public const string CardGrid = "card-grid";
        public const string ColHeaderContent = "col-header-content";
        public const string ColJustifyCenter = "col-justify-center";
        public const string ColJustifyEnd = "col-justify-end";
        public const string ColJustifyLeft = "col-justify-left";
        public const string ColJustifyRight = "col-justify-right";
        public const string ColJustifyStart = "col-justify-start";
        public const string ColOptions = "col-options";
        public const string ColOptionsButton = "col-options-button";
        public const string ColSortAsc = "col-sort-asc";
        public const string ColSortDesc = "col-sort-desc";
        public const string ColTitle = "col-title";
        public const string ColTitleText = "col-title-text";
        public const string ColWidthDraghandle = "col-width-draghandle";
        public const string Container = "table-container";
        public const string DateCell = "date-cell";
        public const string DropContainer = "drop-container";
        public const string DropTitle = "drop-title";
        public const string GoFirst = "go-first";
        public const string GoLast = "go-last";
        public const string GoNext = "go-next";
        public const string GoPrevious = "go-previous";
        public const string GridChipReadonly = "grid-chip-readonly";
        public const string GridEnumFlags = "grid-enum-flags";
        public const string Icon = "table-icon";
        public const string OrderItemsTable = "order-items-table";
        public const string OrderItemsTableWrapper = "order-items-table-wrapper";
        public const string OrdersTable = "orders-table";
        public const string Org = "org";
        public const string PaginationText = "pagination-text";
        public const string Paginator = "paginator";
        public const string PaymentCell = "payment-cell";
        public const string Quickgrid = "quickgrid";
        public const string Root = "m3-table";
        public const string RowActions = "m3-table-row-actions";
        public const string SmartGridContainer = "smart-grid-container";
        public const string SortIndicator = "sort-indicator";
        public const string W3 = "w3";
        public const string Wrapper = "m3-table-wrapper";
    }

    public static class ThemeToggle
    {
        public const string DarkMode = "dark-mode";
        public const string ModeToggle = "m3-mode-toggle";
        public const string ModeToggleFigure = "m3-mode-toggle-figure";
        public const string ModeToggleIcon = "m3-mode-toggle-icon";
    }

}
