<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Configurations>Debug;Release;LocalDebug;Runner;Cluster</Configurations>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Material.Web\Material.Web.csproj" />
    <ProjectReference Include="..\QuickGrid\QuickGrid.csproj" />
    <ProjectReference Include="$(Domain)" Condition="'$(Domain)' != '' and Exists('$(Domain)')" />
    <ProjectReference Include="..\..\Domain\Domain.csproj" Condition="('$(Domain)' == '' or !Exists('$(Domain)')) and Exists('..\..\Domain\Domain.csproj')" />
    <ProjectReference Include="$(SharedKernel)" Condition="Exists('$(SharedKernel)')" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" Condition="('$(SharedKernel)' == '' or !Exists('$(SharedKernel)')) and Exists('..\..\..\Shared\SharedKernel\SharedKernel.csproj')" />

  </ItemGroup>

</Project>

