<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Configurations>Debug;Release;LocalDebug;Runner;Cluster</Configurations>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Columns\ColumnBase.razor">
      <Pack>false</Pack>
    </Content>
    <Content Update="Pagination\Paginator.razor">
      <Pack>false</Pack>
    </Content>
    <Content Update="QuickGrid.razor">
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
